version: "3.8"

services:
  db-mysql:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_DATABASE: mvcdata
    ports:
      - "3306:3306"
